[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
[functions]
  directory = "backend"
  command = "npm run start"
  [[functions.routing]]
    pattern = "/users/*"