[build]
  command = "cd frontend/ && npm run build"
  publish = "frontend/build"
  functions = "backend/build"
  base = "/"
[[redirects]]
  from = "/*"
  to = "/frontend/public/index.html"
  status = 200