[build]
  command = "cd frontend && npm run build"
  publish = "frontend/build"
  base = "/"
[functions]
  directory = "backend/build"
  node_bundler = "esbuild"
[[redirects]]
  from = "/*"
  to = "/frontend/public/index.html"
  status = 200