[build]
  command = "npm run build"
  publish = "build"
  base = "/frontend"
[functions]
  directory = "../backend/build"
  node_bundler = "esbuild"
[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200