[build]
  command = "cd frontend && npm install && npm run build && cd ../backend && npm install"
  publish = "frontend/build"
[functions]
  directory = "backend"
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "express"]
  [functions.command]
    command = "npm run start"
  [functions.routing]
    pattern = "/users/*"